version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'sass-loader'
        versions:
          - '>10'
      - dependency-name: 'sass'
        versions:
          - '>1.35'

