version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install
      - run: node -v
      - run: yarn -v
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - slack/notify:
          template: basic_on_hold_1

workflows:
    build-and-test:
      jobs:
        - build
