version: 2.1
orbs:
  node: circleci/node@4.1.0
  slack: circleci/slack@3.4.2
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - slack/notify:
          # channel: channel_id
          # color: '#42e2f4'
          # mentions: 'foo,bar,'
          # message: This is a custom message notification
          webhook: '${SLACK_WEBHOOK}'
workflows:
    build-and-test:
      jobs:
        - build
