version: 2.1

orbs:
  node: circleci/node@5.0.0
  # SLACK_ACCESS_TOKEN と SLACK_DEFAULT_CHANNEL の設定が必要
  # SLACK_ACCESS_TOKEN は xoxb-12345-12345-X12345 みたいなやつ
  slack: circleci/slack@4.6.2

commands:
  circleci_pass:
    steps:
      - slack/notify:
          event: pass
          # https://github.com/CircleCI-Public/slack-orb/tree/master/src/message_templates
          template: basic_success_1
  circleci_fail:
    steps:
      - slack/notify:
          event: fail
          # https://github.com/CircleCI-Public/slack-orb/tree/master/src/message_templates
          template: basic_fail_1

jobs:
  build:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - circleci_pass
      - circleci_fail

workflows:
    build-and-test:
      jobs:
        - build
